plugins:
  - jest
  - prettier

env:
  node: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
  - "prettier"

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  prettier/prettier: 0
  indent:
    - tab
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
