plugins:
  - jest
  - prettier

env:
  node: true

extends:
  - "eslint-config-airbnb"
  - "plugin:jest/recommended"
  - "prettier"

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  prettier/prettier: "error"
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
